### ISSUE TITLE
How to use Openapi Generator Dart with Dart 3 ?

### ISSUE THREAD

**Issue by linh232323** [gibahjoe/openapi-generator-dart#146]
### Description of the bug

Could not generate project with dart 3

### Steps to reproduce

Using Dart SDK version: 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "macos_arm64"
Run generate and pubspec.yaml as
```
environment:
  sdk: '>=2.7.0 <3.0.0'
```

### Expected behavior

Openapi-Generator-Dart should generate dart 3 project with pubspec env as
```
environment:
  sdk: '>=3.0.0 <4.0.0'
```

### Platform

macOS

### Library version

5.0.2

### Flutter version

3.19.6

### Flutter channel

stable

**Comment by gawi151** [comment]
It's not possible as https://github.com/OpenAPITools/openapi-generator generates only Dart 2 code. Both `vanila` and `dio` versions.

**Comment by Vitaliy-Svinchyak** [comment]
The only problem I faced with dart 3 was that mixins are defined as abstract classes which is not a valid code in dart 3.
I run this bash script after codegen to fix it:
```bash
#!/bin/bash
MODEL_DIRECTORY="./lib/sdk/lib/src/model/"

for file in "$MODEL_DIRECTORY"/*; do
  if [ -f "$file" ]; then
    sed -i '' "s/abstract class _/mixin _/Ig" "$file"
    echo "Moved to mixins in: $file"
  fi
done
```

**Comment by piotruela** [comment]
In my project, I recently spotted that for API models `json_serializable` started to generate `toJson` method implementation using pattern matching. For example:
```dart
      if (instance.paymentRequestId case final value?)
        'payment_request_id': value,
```
Unfortunately, this syntax is invalid in projects with sdk <3.0.0. 
I can workaround that by replacing the sdk constraints inside `pubspec.yaml` but I would love to see this changed in the generator.

**Comment by gibahjoe** [comment]
This is an issue with the main openapi generator library not this library which is just a wrapper. You will have better luck raising an issue here https://github.com/OpenAPITools/openapi-generator/issues

@piotruela 
When you modify the `pubspec`, ensure you commit it to repo (if you are using version control) and include it in the `.openapi-generator-ignore` file so that it is not overwritten next time you run the generator. You should also commit `.openapi-generator-ignore` too.
