### ISSUE TITLE
flutter 3.10.0 -> intl: 0.18.0 requirement

### ISSUE THREAD

**Issue by raegtime** [gibahjoe/openapi-generator-dart#90]
### Description of the bug

the generated pubspec for the api client has a intl 0.17.0 dependency

in flutter 3.10.0 intl has updated to min. version 0.18.0

### Steps to reproduce

generate an api... look in the generated pubspec file

### Expected behavior

intl version 0.18.0

### Platform

macOS

### Library version

4.10.0

### Flutter version

3.10.0

### Flutter channel

stable

**Comment by danijel-tolj** [comment]
You can use dependency overrides until the library dependencies are bumped to be up-to-date.

From documentation: 

If you are having issues with dependencies, what you can do is make use of dependency overrides. This is added to the pubspec.yaml of the generated package and then the pubspec must be added to the .openapi-generator-ignore of the generated package. For example, let's assume you want to override the analyzer package for the generated source

in generatedsource/pubspec.yaml add the following

```
dependency_overrides:
    intl: 0.18.1
```
    
Then in generatedsources/.openapi-generator-ignore, add the below so that the pubspec is not overwritten next time you run source gen

**Comment by thismatters** [comment]
Is there going to be an update to the package to reflect this dependency change or is preventing generation of `pubspec.yaml` a permanent solution?

**Comment by gibahjoe** [comment]
You can check the [latest version](https://pub.dev/packages/openapi_generator_cli) if it fixes this issue as the openapi jar has been updated

**Comment by bartekpacia** [comment]
Unfortunately, this issue still occurs.

**Comment by ricardoboss** [comment]
@bartekpacia I had the same issue. Are you adding `intl` below `dependencies` or as proposed above below `dependency_overrides`?

My working example looks like this:

```
dependencies:
	flutter
		sdk: flutter

	openapi_generator_annotations: ^4.11.0
	openapi:
		path: ./api

dependency_overrides:
	intl: 0.18.1
```
